### ISSUE TITLE
Weights addition: other items to change 

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/riskassessment#121]
After adding the the ability to update weights to the app, there are other items to consider:
- [x] Add documentation about the meaning of the weights (@marlycormar).
- [x] Display the current weights on each tab as well as on the downloaded report (@marlycormar).
          - [ ] Include riskmetric package version 
          - [ ] Include RAA version 
          - [ ] Include date that the information of the package was obtained (i.e., the day the package was uploaded).
- [x] Only show the ui elements to change the weights for authorized users (see PR #119) (@Robert-Krajcik).
- [x] Add button that update the risk and weights per package (see issue #124 and related issue #123) (@Robert-Krajcik).
- [ ] (Optional) Change infoboxes by boxes: infoboxes don't allow shiny inputs or other text besides three pieces of information.

**Comment by Robert-Krajcik** [comment]
Hi @marlycormar 
I'll work on Add button that update the risk and weights per package (see issue #124 and related issue #123).
and create a PR for that

**Comment by marlycormar** [comment]
That sounds good @Robert-Krajcik; I'll take the rest. Since your PR #119 already addresses item _Only show the ui elements to change the weights for authorized users_, I'll add your name there as well.

**Comment by AARON-CLARK** [comment]
> [ ] Add documentation about the meaning of the weights (@marlycormar).

Wasn't this completed with #128

**Comment by aclark02-arcus** [comment]
Super stale issue. Closing!
