### ISSUE TITLE
Make hex or favicon in conjunction with `riskmetric`

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#161]
Hi team, 

I'm in the process of converting RAA into a package, and realized we'll need some sort of branding to include with our beta release... so some icon or hex that people can associate with our package. From there, we'll be able to display that in the app, on the browser tab, and in our documentation (README). 

I've had great success making a hex or two with colin fay's [hexmake](https://connect.thinkr.fr/hexmake/) application. If you are feeling creative, feel free to develop something that encompasses the essence of the app! I checked `riskmetric` and it appears they don't have any hex or icon branding, so we'll have to create something original!

Thanks! Feel free to brainstorm and share drafts here!

**Comment by Robert-Krajcik** [comment]
OK I'm searching for an icon that encompasses risk assessment for R packages.

**Comment by Robert-Krajcik** [comment]
These are all royalty-free stock photos, to give you some ideas.
I'm trying to find something that would be relatively easy to create.
I like the first one the most.

![image](https://user-images.githubusercontent.com/75215958/150201001-7fc825c7-b496-4cf7-96d3-ee5d12a3b637.png)
![image](https://user-images.githubusercontent.com/75215958/150201142-57a0bfe5-9ea4-4dc2-9c0e-6c40d066888c.png)
![image](https://user-images.githubusercontent.com/75215958/150201242-2d9a8e49-5c4f-4275-a885-718cf9aaf272.png)
![image](https://user-images.githubusercontent.com/75215958/150201310-5eebb8c9-1a60-4874-8789-2156a1ee49ce.png)

**Comment by Robert-Krajcik** [comment]
Or maybe use this one and put the four wooden blocks to the left

![image](https://user-images.githubusercontent.com/75215958/150201824-00000558-3b8a-4fae-b241-b654470179e1.png)

**Comment by AARON-CLARK** [comment]
Please be cognizant of the design the riskmetric team is brainstorming too. Collectively, our hex logos should be aesthetically similar. See: https://github.com/pharmaR/riskmetric/issues/233

**Comment by Jeff-Thompson12** [comment]
I've come across a couple images using a balance scale of some sort. I think a balance scale is a really simple visual that communicates a lot about what the risk assessment application is all about.

https://www.123rf.com/photo_60634867_risk-assessment-icon-symbolizing-with-scale-weighting-alphabet-cubes-of-risk-in-red.html

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, I like the idea of a scale. It brings back memories of the original Charlie & the Chocolate Factory, when the geese were sorting the golden eggs, and [Veruca Salt was deemed a "bad" egg](https://www.google.com/imgres?imgurl=https%3A%2F%2Fmedia.tenor.com%2Fm2mDk9aa_lYAAAAC%2Fi-want-a-golden-goose-now-willie-wonka.gif&imgrefurl=https%3A%2F%2Ftenor.com%2Fsearch%2Fveruca-salt-golden-egg-gifs&tbnid=addoNDr-m_Kh7M&vet=12ahUKEwjoyYn5zcL7AhWGsFMKHd9TDAEQMygcegUIARCGAQ..i&docid=55Fv8jAktDkNfM&w=498&h=333&q=willy%20wonka%20bad%20egg&ved=2ahUKEwjoyYn5zcL7AhWGsFMKHd9TDAEQMygcegUIARCGAQ), haha. Here is a mock up of what that scale looked like:

![image](https://user-images.githubusercontent.com/17878953/203413861-16212db5-1887-43db-813a-b06b51362355.png)

![image](https://user-images.githubusercontent.com/17878953/203414172-4d013771-8f2d-4ce3-b095-30c8dd05b668.png)

I like this illustration because it implies there is sorting happening, measuring risk, and even doing it as a community (several geese working together)! Although, we'd obviously want to stay away from language like "good" and "bad". Reflecting on this, I now I understand Eric's hex logos which included different color hexes, to imply sorting R packages into similar groups (based on risk).

**Comment by AARON-CLARK** [comment]
Speaking of a scale, perhaps lady justice holding the scales is more applicable. She is not only more globally recognizable, but has the same goal of sorting the good/bad eggs, but in a more communal effort (via the court system). In our context, each company/organization uses the `riskassessment` app to set up the infrastructure for their own court system. So maybe her + sorted hexes would make sense.

![image](https://user-images.githubusercontent.com/17878953/203419676-08ec12b4-68fa-4f5a-b53e-24f92eb3fcd4.png)

Thanks, I'm just jotting down ideas!

**Comment by imran3004** [comment]
![hex-risk assessment](https://user-images.githubusercontent.com/8725681/203801695-1fde7e3c-85ee-4f67-8550-b56a71d81940.png)

Just an idea. Will need work.

1. Image will have to be an SVG so that it scales well.
2. Colour gradients will have to be corrected.

**Comment by AARON-CLARK** [comment]
Hi all,

I made a working draft based on everyone's clear interest in having some sort of scale/gauge. For `riskassessment`, I think having three distinct colors in the scale/gauge highlights the app's goal is to categorize packages into three groups: low, medium, and high risk. I was thinking the `riskmetric` version could have a more continuous gradient of colors to reflect the quantitative nature of the risk score. If people thinks that's a good idea, let me know and I'll try to work something up for `riskmetric`. I made a light and dark version below for fun:

![image](https://user-images.githubusercontent.com/17878953/205717752-0de3adfb-41c6-413a-aa3f-b7a3d72a00bc.png)

I think another idea to make the hex logos look different would be to share the same color for the work "risk" in the title, but have different colors for "metric" vs "assessment". 

I used [this icon](https://www.flaticon.com/free-icon/risk_2176912?term=risk&related_id=2176912#) as a base, but customized it quite a bit to include embedded hexes

**Comment by Robert-Krajcik** [comment]
I like these, @AARON-CLARK 
I think they embody the three overall levels of risk we have in the app,
and it's not an overly-complicated design.  Think good _**gestalt**_
(And if you were selling a house, you would go for the light pastel background on the right 😁 )

**Comment by imran3004** [comment]
Good work @AARON-CLARK ! I prefer the one on the right for the light-coloured background; it looks like it contrasts better with the text.

Also, I wonder if the arrow indicator would be more conspicuous if we had it in filled black instead of only a black border.

**Comment by AARON-CLARK** [comment]
Hi all,

Along my thought pattern shared above, here are a few `{riskmetric}` ideas, with a continuous color gradient, and some corresponding `{riskassessment}` ideas (below) as well. You'll notice I created a bunch of border/hex/title color variations to choose from. I presented these to the `{riskmetric}` team today and they chose 3 & 4 (top right and bottom left) as contenders. We'll submit these to the RValHub Exec committee next week for a vote. The intent is make sure that one of the logos is light and one is dark, so they are more distinguishable from one another. For example, if they are both white, the hex logos will be too similar and difficult to tell apart. So we'll make sure one is dark grey and one is white or cream-colored.

![image](https://user-images.githubusercontent.com/17878953/206248572-a39907d7-9e56-4586-afe6-f9bd9785c9be.png)

And for the `{riskassessment}` options: I changed the gauge's needle to a cursor, and enclosed the gauge inside a browser window. Of course, the hex tiles on the gauge only show up in three colors, to reflect the user decision, assigning pkgs with a 'low', 'medium', or 'high' risk category.

![image](https://user-images.githubusercontent.com/17878953/206250266-6085bb3d-0c06-4bc0-b392-7d9c301e496a.png)

Thoughts?

**Comment by AARON-CLARK** [comment]
fyi, I consolidated the decision down to the two options, the hex logo pair on the left or the right: which do you prefer?

![image](https://user-images.githubusercontent.com/17878953/206290732-ad6eda64-dcf9-4558-ae7d-ef5b3977b65d.png)

**Comment by imran3004** [comment]
We have issue #276 for allowing custom categories. Do you think the 3 categories reflected on the icon will be incongruous once this feature is implemented?

**Comment by Jeff-Thompson12** [comment]
I feel like I was asked to give my favorite color. I don't really have a preference. The both look great Aaron. If I had to choose, I would say that the light background with the dark window is more aesthetically pleasing to me than the dark background with a light window. So I guess I prefer option number 2.

**Comment by AARON-CLARK** [comment]
> Do you think the 3 categories reflected on the icon will be incongruous

@imran3004, that's a good point! I think we're okay as long as we it conveys pkg-hexes being grouped, which is the main intent/goal of the app. So, regardless of if the user wants to change it to 2 or 10 categories, I think this logo is still applicable. Also, the default & recommended behavior will be 3 categories.

**Comment by Robert-Krajcik** [comment]
Is the top row for the `riskmetric` app the the bottom for our `riskassessment`?
Given a choice, I prefer lighter backgrounds.

**Comment by AARON-CLARK** [comment]
> Is the top row for the `riskmetric` app the the bottom for our `riskassessment`?

@Robert-Krajcik: Correct, but if they RValHub Exec team chooses light for one pkg, the other will have to go dark. That's why I asked if you like the pair on the left of the pair on the right.

**Comment by AARON-CLARK** [comment]
Latest Iterations. If these are suitable, we'll use the web browser as the favicon for the app.



![Image](https://user-images.githubusercontent.com/17878953/211845487-ccd2ad90-1c7a-4217-bfdb-40987e5eac4b.png)

**Comment by AARON-CLARK** [comment]
closed with #349
