### ISSUE TITLE
Loading csv files with misspelled/non-existent package gives error in uploadPackage.R

### ISSUE THREAD

**Issue by Robert-Krajcik** [pharmaR/riskassessment#233]
I am starting with a clean DB -- current with #232 Add break between progress message and details

loading the following
package | version
glue | 0.0.0
tidyr | 0.0.0
shiny | 0.0.0
ElCerdo | 0.0.0

We used to check for misspelled/non-existent packages.  What happened?

![image](https://user-images.githubusercontent.com/75215958/160679082-04b98d96-c5ef-4a93-b637-0a423722d61a.png)

**Comment by Jeff-Thompson12** [comment]
@Robert-Krajcik Was it working after "Server/uploadpackage.R" and "UI/uploadpackage.R" were combined into "R/uploadPackage.R"? Looking at the history, it looks like not all of the code was copied into the new file.

**Comment by Jeff-Thompson12** [comment]
I'm looking at 673d98a05f3210085816c2bee9aebfb1f55ed1f7 and 99443839fc6d74ea601e77746e1c53f6c4f46ab6.

**Comment by Robert-Krajcik** [comment]
I'm not sure when this broke @Jeff-Thompson12 
But we need some way of checking for misspelled names.

**Comment by aclark02-arcus** [comment]
closed with #240
