### ISSUE TITLE
New feature: code explorer

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/riskassessment#242]
(see Tilo's email)

**Comment by AARON-CLARK** [comment]
"GSK on the other hand shared a code explorer feature. It allows the user to look in to function definitions, and find every instance where the function is used. I’ll follow up with them to see if they can share a presentation or the code."

So, they augmented the app to create a code explorer? Just to make sure I understand, if they were reviewing `haven`, they have a tab that will allow them to search through function names & see the code for `read_sas()`? That is definitely something that goes beyond `riskmetric`’s gathering of package metrics and allows users to get into the nitty gritty. Though we should probably discuss if this feature is a good fit for `riskassessment`, does GSK know they could have just opened up an issue on our GitHub and we could have worked on it? Or they could always submit a PR.

**Comment by marlycormar** [comment]
Hey @AARON-CLARK, I think I didn't follow up on your comment. They recently got permission from GSK to share the code and I suggested to do so as an issue. 

Let's us discuss further in our next meeting; I am not sure either whether this is a good feature for the app.

**Comment by AARON-CLARK** [comment]
See https://youtu.be/P2m6RmVViu0?t=2792 for context.

**Comment by Jeff-Thompson12** [comment]
Closing because it is being tracked in #498
