### ISSUE TITLE
Consider adding more CI/CD workflows

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#270]
Details: https://pharmaverse.github.io/admiralci/main/

Consider:
 - [ ] lintr.yml
- [x] code-coverage.yml
- [ ]  links.yml
- [ ]  man-pages.yml (defer since running `run_dev.R` is apart of our daily workflow - 1/31/23)
- [ ]  r-pkg_validation.yml (defer - 1/31/23)
- [x]  readme-render.yml
- [x]  spellcheck test
- [ ]  style.yml

**Comment by borgmaan** [comment]
@AARON-CLARK  A few thoughts/questions on these before moving forward:


### styling/linting

Is there interest in making to commitment to adhere to a workflow that includes this? If so, a first step would be getting the current code base compliant to prepare for turning on the actions. Running `lintr::lint_package()` on the `dev` branch currently flags 1,919 lines with issues that should be resolved. This drops to 533 after running `styler::style_pkg()`. We'd want to tackle these in one form or another (e.g. fixing, ignoring, changing linting rules, etc.) prior to turning on a GHA lint-checker that fails if any discrepancies are found. 

Personally, I think this is a good idea. However, the effort, discussion, and decision making involved in the prep probably warrants its own issue as it is not trivial.

### spelling

[`tests/spelling.R`](https://github.com/pharmaR/riskassessment/blob/master/tests/spelling.R) looks like it is intended to check spelling. Is that true? If so, we can likely check that off the list.

**Comment by AARON-CLARK** [comment]
> [`tests/spelling.R`](https://github.com/pharmaR/riskassessment/blob/master/tests/spelling.R) looks like it is intended to check spelling. Is that true? If so, we can likely check that off the list.

Looks like it does, but we don't have the `error` arg set to `TRUE` which would actually alert us to spelling mistakes! I'll submit a PR to make this small change.

**Comment by Xyarz** [comment]
A draft for the lintr.yaml could be [this](https://github.com/Boehringer-Ingelheim/oncomsm/blob/main/.github/workflows/lint.yml)

**Comment by aclark02-arcus** [comment]
closing since our other GHA options already have their own dedicated issues.
