### ISSUE TITLE
Report download not working with `{fontawesome}` Version `0.4.0`

### ISSUE THREAD

**Issue by Jeff-Thompson12** [pharmaR/riskassessment#275]
The download reports are not working on MAC computers. This appears to be related to two issues.

1. The Community Metrics are not being created because of an empty select. (See #283)
2. The icons are causing problems when the Rmd file is being knit.

Problem 1 can be easily handled.
[comm_patch.txt](https://github.com/pharmaR/risk_assessment/files/9983788/comm_patch.txt)

Problem 2 might require a bit more pandoc knowledge.

**Comment by AARON-CLARK** [comment]
Hey @Jeff-Thompson12, could you update this issue and separate it into two so that problem 1 could be solved with a PR? Thanks!

**Comment by Jeff-Thompson12** [comment]
Problem one is being addressed in #283 

This issue is being left open until a solution to download HTML reports on Mac computers is resolved.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK this is not a Mac issue. It is a `{fontawesome}` package issue. Version `0.4.0` does not include files "fa-v4compatibility.tff" and "fa-v4compatibility.woff2" files. While you can manually search for these files online and add them to the appropriate folder, this is not desirable behavior.

**Comment by Jeff-Thompson12** [comment]
See https://github.com/rstudio/fontawesome/issues/99

**Comment by Jeff-Thompson12** [comment]
@imran3004 for the time being I would suggest loading an older version of `{fontawesome}`. Version `0.3.0` was working for me.

**Comment by imran3004** [comment]
Yes `fontawesome` 0.3.0 is working on my Mac. I am able to generate the HTML reports.

**Comment by AARON-CLARK** [comment]
will be solved with #48

**Comment by AARON-CLARK** [comment]
Just thought of this: #48 will only resolve this issue for developers, not users. Thus, shouldn't we add `fontawesome (== 0.3.0)` to the suggest field until this issue is resolved with `{fontawesome}`?

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK BTW, version 5.0 of `{fontawesome}` has been released and resolves this issue. Not sure if we want to leave the checks in place but maybe only provide the notes and modals if the user is using version 4.0. Thoughts?

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, that makes sense to me.
