### ISSUE TITLE
Design unit tests for each function

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#295]
Hi all, I took the time to group our functions into similar groups. The hope is that we can all contribute to writing `testthat` tests. Please review some of the categories below and feel free to volunteer for a certain group/ category of test. I submit a PR (#302) that will actually re-organize some of these functions to new utils files so they are easier to track down in the `R/` folder. Please stay tuned until it is merged into `dev`, thank you!

|Group     |Function                            |Developer |PR submitted | PR Reviewed |
|:---------|:--------------------------------|:---------|:---------|:---------|
|app            |run_app                          |          |         |         |
|get db         |dbSelect                         |    Robert-Krajcik      |   X    |    X    |
|get db         |get_cm_comments                  |  Robert-Krajcik        |   X    |    X    |
|get db         |get_comm_data                    |   Robert-Krajcik       |   X    |    X    |
|get db         |get_metric_weights               |   Robert-Krajcik       |   X    |    X    |
|get db         |get_mm_comments                  |   Robert-Krajcik       |   X    |    X    |
|get db         |get_mm_data                      |   Robert-Krajcik       |   X    |    X    |
|get db         |get_overall_comments             |   Robert-Krajcik       |   X    |    X    |
|get db         |get_pkg_info                     |  Robert-Krajcik        |   X    |    X    |
|get db         |weight_risk_comment              |  Robert-Krajcik        |   X    |    X    |
|insert db      |dbUpdate                         |  Robert-Krajcik        |    X   |    X  |
|insert db      |insert_community_metrics_to_db   |  Robert-Krajcik        |    X    |   X    |
|insert db      |insert_maintenance_metrics_to_db |  Robert-Krajcik        |    X   |    X    |
|insert db      |generate_comm_data            | Aaron Clark |   X    |     X    |
|insert db      |insert_pkg_info_to_db            |  Robert-Krajcik        |   X     |   X     |
|insert db      |update_metric_weight             |  Robert-Krajcik        |    X     |   X     |
|insert db      |upload_package_to_db             |  Robert-Krajcik        |    X    |    X    |
|metric modules |addCommentServer                 |borgmaan|         |         |
|metric modules |addCommentUI                     |borgmaan|         |         |
|metric modules |communityMetricsServer           |    Robert-Krajcik                |   X    |   X   |
|metric modules |communityMetricsUI               |    Robert-Krajcik                |   X   |    X   |
|metric modules |decision_automation|Jeff Thompson|   X    |   X   |
|metric modules |decision_automation|Jeff Thompson|   X   |    X   |
|metric modules |maintenanceMetricsServer         |     Robert-Krajcik               |   X    |   X   |
|metric modules |maintenanceMetricsUI             |    Robert-Krajcik                |   X    |   X   |
|metric modules |metricBoxServer                  |  Lars       |         |         |
|metric modules |metricBoxUI                      |  Lars        |         |         |
|metric modules |metricGridServer                 |          |         |         |
|metric modules |metricGridUI                     |          |         |         |
|metric modules |viewCommentsServer               | Imran         |         |         |
|metric modules |viewCommentsUI                   |     Imran     |         |         |
|other modules  |assessmentInfoServer             |  Aaron         |         |         |
|other modules  |assessmentInfoUI                 | Aaron  |         |         |
|other modules  |databaseViewServer               |Jeff Thompson|X|X|
|other modules  |databaseViewUI                   |Jeff Thompson|X|X|
|other modules  |introJSServer                    |Jeff Thompson|X|X|
|other modules  |introJSUI                        |Jeff Thompson|X|X|
|other modules  |reportPreviewServer              |    Robert-Krajcik              |   X    |   X    |
|other modules  |reportPreviewUI                  |    Robert-Krajcik              |   X    |   X    |
|other modules  |reweightViewServer               |Jeff Thompson|X|X|
|other modules  |reweightViewUI                   |Jeff Thompson|X|X|
|other modules  |sidebarServer                    |    Robert-Krajcik              |   X   |   X   |
|other modules  |sidebarUI                        |    Robert-Krajcik               |   X   |    X   |
|other modules  |uploadPackageServer              | borgmaan |         |         |
|other modules  |uploadPackageUI                  |  borgmaan |         |         |
|startup        |add_tags                         |Jeff Thompson|    X   |    X  |
|startup        |app_theme                        |Jeff Thompson|    X   |    X  |
|startup        |create_credentials_db            |Jeff Thompson|    X   |    X  |
|startup        |create_db                        |Jeff Thompson|    X   |    X  |
|startup        |initialize_raa                   |Jeff Thompson|    X   |    X  |
|util helpers   |auto_font                        |  Aaron        |   X     |         |
|util helpers   |build_comm_cards                 |Aaron        |        |         |
|util helpers   |build_comm_plotly                | Scott Schumacker         |         |         |
|util helpers   |decision_automation| Jeff Thompson|X|X|
|util helpers   |get_date_span                    | Imran         | Yes        |    Yes     |
|util helpers   |get_latest_pkg_info              |   Lars       |   Yes      |         |
|util helpers   |getTimeStamp                     |   Lars       |   Yes      |         |
|util helpers   |pipe                             |          |         |         |
|util helpers         |showComments                     |          |         |         |
|util helpers   |showHelperMessage                |  Imran        |  Yes       |    Yes     |

**Comment by AARON-CLARK** [comment]
Robert volunteers for db-related functions...

**Comment by borgmaan** [comment]
It may be helpful to consider adopting [`shinytest2`](https://rstudio.github.io/shinytest2/index.html) to help hit the code coverage goals. This approach can ease the testing burden on complex applications like this -- especially when it comes to testing modules that may need significant test setup/mocking or have difficult to test return values. 

You can see an initial example of this approach on the [`ab-add-shinytest2`](https://github.com/pharmaR/risk_assessment/tree/ab-add-shinytest2) branch. [`test-uploadPackage.R`](https://github.com/pharmaR/risk_assessment/blob/eaf33a386f3f0ec95798e50a8256b5eeefe2e5aa/tests/testthat/apps/app1/tests/testthat/test-uploadPackage.R) includes a basic test for the components in [`uploadPackage.R`](https://github.com/pharmaR/risk_assessment/blob/ab-add-shinytest2/R/uploadPackage.R) to confirm the packages in the upload summary table match those provided in the uploaded CSV file.  


This test structure passes `devtools::check` and is `covr`-compatible. Below is the output of `covr::package_coverage` before and after adding the logic in `test-uploadPackage.R`. 

I briefly discussed this idea with @AARON-CLARK and am interested in feedback from others on the approach. I think it can be an effective way to increase the overall test coverage while simultaneously simplifying the tests being written. 

Before: 

```
> covr::package_coverage()
riskassessment Coverage: 15.84%
R/addComment.R: 0.00%
R/app_server.R: 0.00%
R/metricBox.R: 0.00%
R/metricGrid.R: 0.00%
R/reweightView.R: 0.00%
R/run_app.R: 0.00%
R/viewComments.R: 0.00%
R/reportPreview.R: 0.42%
R/communityMetrics.R: 1.72%
R/maintenanceMetrics.R: 2.44%
R/utils.R: 8.56%
R/uploadPackage.R: 10.55%
R/databaseView.R: 10.82%
R/utils_insert_db.R: 12.66%
R/sidebar.R: 14.98%
R/utils_get_db.R: 26.83%
R/assessmentInfo.R: 37.00%
R/introJS.R: 46.15%
R/utils_startup.R: 70.29%
R/app_config.R: 100.00%
R/app_ui.R: 100.00%
```


After:

```
> covr::package_coverage()
riskassessment Coverage: 43.79%
R/metricBox.R: 0.00%
R/utils.R: 8.56%
R/metricGrid.R: 16.67%
R/reportPreview.R: 18.83%
R/databaseView.R: 19.05%
R/reweightView.R: 19.42%
R/viewComments.R: 21.05%
R/addComment.R: 21.62%
R/utils_get_db.R: 37.80%
R/run_app.R: 44.83%
R/sidebar.R: 46.48%
R/communityMetrics.R: 55.17%
R/maintenanceMetrics.R: 58.54%
R/app_server.R: 59.17%
R/utils_startup.R: 70.29%
R/uploadPackage.R: 74.87%
R/utils_insert_db.R: 81.01%
R/assessmentInfo.R: 84.00%
R/app_config.R: 100.00%
R/app_ui.R: 100.00%
R/introJS.R: 100.00%
```

**Comment by Jeff-Thompson12** [comment]
@borgmaan I definitely agree that we want to use a testing strategy such as `shinytest2` to more fully test the application/package.

I have not been able get any `shinytest2` tests to work for me though. I tried running the tests on [ab-add-shinytest2](https://github.com/pharmaR/risk_assessment/tree/ab-add-shinytest2), and below is my experience.

I can only get `devtools::test()` to pass if I build/install `{riskassessment}` into my R library. The test fails for me if I simply do `devtools::load_all()` without building/installing `{riskassessment}`.

If I run `devtools::check()` using the RStudio IDE option, it exits with status 1. It does not give any indication it failed when running `devtools::check()` in the console, but seems to exit at the same point.

Am I missing a step or procedure for testing with `shinytest2`?

**Comment by borgmaan** [comment]
@Jeff-Thompson12  -- thanks for testing it out!

> Am I missing a step or procedure for testing with shinytest2?

Issues will pop up if your R session cannot access a Chrome binary. This doesn't seem to be the case as you were able to run `devtools::test()` after locally installing the package. The following command will throw an error if you do not have access to a Chrome-like binary: `chromote::ChromoteSession$new()`

I temporarily added dependency tracking with `renv` to try to help troubleshoot. I was able to step through the following workflow on 2 separate devices and get `devtools::check()` to pass:

1. Clone a clean copy of repo
2. Check out `ab-add-shinytest2`
3. Run `renv::restore()` in console
4. Run `devtools::check()` in console

Can you try this out and let me know if you are still experiencing the *status 1* exit you were seeing before?

<details>
  <summary>Here's my devtools::check() output for reference</summary>

```
> devtools::check()
══ Documenting ═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
ℹ Updating riskassessment documentation
ℹ Loading riskassessment

══ Building ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Setting env vars:
• CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
• CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
• CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX14FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX17FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX20FLAGS: -Wall -pedantic -fdiagnostics-color=always
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\aborgman\tmp\risk_assessment/DESCRIPTION' (738ms)
─  preparing 'riskassessment': (535ms)
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts (376ms)
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'riskassessment_0.0.1.9012.tar.gz'
   
══ Checking ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Setting env vars:
• _R_CHECK_CRAN_INCOMING_REMOTE_               : FALSE
• _R_CHECK_CRAN_INCOMING_                      : FALSE
• _R_CHECK_FORCE_SUGGESTS_                     : FALSE
• _R_CHECK_PACKAGES_USED_IGNORE_UNUSED_IMPORTS_: FALSE
• NOT_CRAN                                     : true
── R CMD check ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─  using log directory 'C:/Users/aborgman/AppData/Local/Temp/RtmpyeABHy/file5d70293c5232/riskassessment.Rcheck' (697ms)
─  using R version 4.2.2 (2022-10-31 ucrt)
─  using platform: x86_64-w64-mingw32 (64-bit)
─  using session charset: UTF-8
─  using options '--no-manual --as-cran' (350ms)
✔  checking for file 'riskassessment/DESCRIPTION'
─  this is package 'riskassessment' version '0.0.1.9012'
─  package encoding: UTF-8
✔  checking package namespace information
N  checking package dependencies (1.9s)
   Imports includes 33 non-default packages.
   Importing from so many packages makes the package vulnerable to any of
   them becoming unavailable.  Move as many as possible to Suggests and
   use conditionally.
✔  checking if this is a source package ...
✔  checking if there is a namespace
✔  checking for executable files (1.5s)
✔  checking for hidden files and directories ...
✔  checking for portable file names ...
✔  checking serialization versions
─  checking whether package 'riskassessment' can be installed ... [22s] OK (22s)
✔  checking installed package size (337ms)
✔  checking package directory (2.5s)
✔  checking for future file timestamps ... 
✔  checking DESCRIPTION meta-information (984ms)
✔  checking top-level files
✔  checking for left-over files
✔  checking index information
✔  checking package subdirectories ... 
✔  checking R files for non-ASCII characters ... 
✔  checking R files for syntax errors (389ms)
✔  checking whether the package can be loaded (4.8s)
✔  checking whether the package can be loaded with stated dependencies (4.5s)
✔  checking whether the package can be unloaded cleanly (4.8s)
✔  checking whether the namespace can be loaded with stated dependencies (4.1s)
✔  checking whether the namespace can be unloaded cleanly (5s)
✔  checking loading without being on the library search path (5.8s)
N  checking dependencies in R code (4.3s)
   Namespace in Imports field not imported from: 'pkgload'
     All declared Imports should be used.
   Unexported object imported by a ':::' call: 'shinymanager:::admin_ui'
     See the note in ?`:::` about the use of this operator.
✔  checking S3 generic/method consistency (6.8s)
✔  checking replacement functions (4.2s)
✔  checking foreign function calls (3.8s)
─  checking R code for possible problems ... [22s] OK (21.9s)
✔  checking Rd files (642ms)
✔  checking Rd metadata ... 
✔  checking Rd line widths ... 
✔  checking Rd cross-references (498ms)
✔  checking for missing documentation entries (4.7s)
✔  checking for code/documentation mismatches (12.2s)
✔  checking Rd \usage sections (5.8s)
✔  checking Rd contents ... 
✔  checking for unstated dependencies in examples ... 
✔  checking R/sysdata.rda (403ms)
✔  checking examples (5s)
W  checking for unstated dependencies in 'tests' (4s)
   '::' or ':::' import not declared from: 'fs'
─  checking tests (344ms)
✔  Running 'spelling.R'
X  Comparing 'spelling.Rout' to 'spelling.Rout.save' ...
   6,19d5
   < Potential spelling errors:
   <   WORD          FOUND IN
   < Aravind       riskassessment-package.Rd:33
   <               README.md:156
   < DOCX          NEWS.md:11
   < Imran         riskassessment-package.Rd:41
   < MetricBox     auto_font.Rd:27
   < Munshi        riskassessment-package.Rd:41
   < Reddy         riskassessment-package.Rd:33
   <               README.md:156
   < dbSelect      NEWS.md:17
   < dev           create_credentials_dev_db.Rd:5,13
   < fontawesome   NEWS.md:15
   < testthat      NEWS.md:17
    [44s] OKtestthat.R'
   * checking for non-standard things in the check directory ... OK
   * checking for detritus in the temp directory ... OK
   * DONE
   
   Status: 1 WARNING, 2 NOTEs
   See
     'C:/Users/aborgman/AppData/Local/Temp/RtmpyeABHy/file5d70293c5232/riskassessment.Rcheck/00check.log'
   for details.
   
   
   Warning message:
   In normalizePath(path.expand(path), winslash, mustWork) :
     path[3]="C:/Users/aborgman/AppData/Local/Temp/RtmpyeABHy/renv-system-library": The system cannot find the file specified
── R CMD check results ────────────────────────────────────────────────────────────────────────────────────────── riskassessment 0.0.1.9012 ────
Duration: 3m 3.1s

❯ checking for unstated dependencies in 'tests' ... WARNING
  '::' or ':::' import not declared from: 'fs'

❯ checking package dependencies ... NOTE
  Imports includes 33 non-default packages.
  Importing from so many packages makes the package vulnerable to any of
  them becoming unavailable.  Move as many as possible to Suggests and
  use conditionally.

❯ checking dependencies in R code ... NOTE
  Namespace in Imports field not imported from: 'pkgload'
    All declared Imports should be used.
  Unexported object imported by a ':::' call: 'shinymanager:::admin_ui'
    See the note in ?`:::` about the use of this operator.

0 errors ✔ | 1 warning ✖ | 2 notes ✖
warning messages from top-level task callback '3'
Warning message:
the renv sandbox was deleted; it will be re-generated 
```
</details>

**Comment by borgmaan** [comment]
@Jeff-Thompson12 FYI -- I also opened a draft PR (#322) and can confirm all the CI/CD checks are passing there  (sorry... should have done this initially... still learning your dev workflow). 

Please let me know if you are still having issues getting things to run. Happy to hop on a screen sharing session to help troubleshoot!

**Comment by imran3004** [comment]
Just a heads up... tests created with `shinytest2` will not be reflected in the code coverage provided by `covr`. 

Reference: [No code coverage for {shiny} applications](https://github.com/rstudio/shinytest2/issues/268)

**Comment by borgmaan** [comment]
@imran3004 -- that is not the behavior I have been seeing. The `shinytest2`-related tests are bumping coverage as expected. A good example can be seen on the [PR](https://github.com/pharmaR/riskassessment/pull/333) for the `addComment` modules. The [`codecov` report](https://github.com/pharmaR/riskassessment/pull/333/#issuecomment-1379383994) shows the expected coverage increases  despite the tests being driven by our `shinytest2` approach.

**Comment by AARON-CLARK** [comment]
Just an update, as of #368, our test coverage is [above 80%](https://github.com/pharmaR/riskassessment/pull/368#issuecomment-1402077723):

![image](https://user-images.githubusercontent.com/17878953/215560783-98894b64-be5b-401b-9b1a-83f46048da26.png)

**Comment by AARON-CLARK** [comment]
Closing since we attained 80% (at some point in the past).
