### ISSUE TITLE
App's metrics not sync'd with all of `riskmetric` metrics

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#299]
There are metrics being assessed by `riskmetric` that we are not taking into consideration when calculating a risk score:

- [ ] `r_cmd_check` - is this operational? Is this only R CMD Checks performed by CRAN/ Bioconductor? For example, is this checking a GitHub Action workflow?

![image](https://user-images.githubusercontent.com/17878953/204355709-833af5ab-bd9b-46b8-9e6d-cb65e5aba996.png)

- [ ] `remote_checks` - I've seen this work. Here is an example for `tidyCDISC`:

![image](https://user-images.githubusercontent.com/17878953/204355634-d04e8e8e-e5a3-4fef-b03d-a0ac8c6a1827.png)

- [ ] `exported_namespace` - works sometimes. Doesn't work for `tidyCDISC` but it exports a ton of functions. Also, I'm not entirely sure why having exported functions would be a good metric to assess package risk??? I tried to look through `riskmetrics` GitHub issues and couldn't find any. I did find one (43) regarding documented examples for each function, which makes more sense than just measuring the presence of exported objects. Here is example output for `haven`:

![image](https://user-images.githubusercontent.com/17878953/204356128-c5402519-949b-4f90-aae7-b021c9b3727c.png)

- [ ] `covr_coverage` - works sometimes (I think)

![image](https://user-images.githubusercontent.com/17878953/204356006-cdc57591-5ae9-439e-b846-5298592b5840.png)

Here is the code used to check each:
```
"ex <- haven" %>%
  pkg_ref() %>%
  as_tibble() %>%
  pkg_assess()
View(ex)
```

At the end of the day, prefer a solution the automatically integrates these any & all new metrics into the app & databases vs a manual solution.

**Comment by aclark02-arcus** [comment]
This is a duplicate.
