### ISSUE TITLE
Need other visual indicators for Pkg Decision on Database Tab

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#337]
@Jeff-Thompson12 mentioned it may be nice to have other visual indicators besides colors, like an exclamation point or a thumbs up or emoji faces next to the each decision on the database tab.

_Originally posted by @AARON-CLARK in https://github.com/pharmaR/riskassessment/issues/325#issuecomment-1372475500_

**Comment by Robert-Krajcik** [comment]
Waiting for PR #459 Custom Decision Categories to get merged.

**Comment by Robert-Krajcik** [comment]
Hey @AARON-CLARK 
I'm thinking this might be better incorporated into PR #459 Custom Decision Categories.
I know that PR is HUGE already but I think this ties into it.
Your thoughts?

**Comment by AARON-CLARK** [comment]
@Robert-Krajcik, you are right. But I think we're trying to get that PR pushed through, so we can still follow up on this issue after 459 is merged.

@Jeff-Thompson12, what do you think? Do you think we could give users the option to specify an icon name in the config file for each decision category, if desired? It may add unnecessary complexity to the config file. Perhaps it's better if integrated at the same time #465 where we'll allow custom coloring to decision categories.

**Comment by Jeff-Thompson12** [comment]
I think we are firmly at the point where any enhancements to #459 need to be follow up PRs.

**Comment by aclark02-arcus** [comment]
I'm going to close this for now since the decision names and colors are pretty informative as it is.
