### ISSUE TITLE
Edits to "Pkg Delete" Option

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#366]
Hi @Robert-Krajcik,

I was just starting a review your PR #352 when @Jeff-Thompson12 finished his review and merged. No big deal, but I thought I'd add my comments here:

First, could we change the color of this button so that it really pops against the rest of the page? I think we should visually indicate that this button is "special". Maybe a light blue?

![image](https://user-images.githubusercontent.com/17878953/214159951-f03bfa59-b3a8-4725-a61d-03b9cd097725.png)

Secondly, I thought it probably matters to include the pkg's version number in this summary table since we are storing it in the DB:

![image](https://user-images.githubusercontent.com/17878953/214160430-54183b07-136f-43b1-a456-e0d0d546b5eb.png)

**Comment by Robert-Krajcik** [comment]
OK I'll create a PR for these, @AARON-CLARK

**Comment by Robert-Krajcik** [comment]
Here is the updated "Remove Package(s)" button
![image](https://user-images.githubusercontent.com/75215958/214323152-0a14ed7a-3bce-4a41-9216-edeb9b47670c.png)

**Comment by Robert-Krajcik** [comment]
adding version to "Summary of Removed Packages"
![image](https://user-images.githubusercontent.com/75215958/214327199-24b7cc18-4dc1-4af2-9ab8-d09657c4e245.png)

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK & @Robert-Krajcik 

I know the PR addressing this issue has already been merged, but can we change the border to the delete button as well? Red border on blue background is offending my eyes.

**Comment by AARON-CLARK** [comment]
> can we change the border to the delete button as well?

@Jeff-Thompson12, of course!

**Comment by AARON-CLARK** [comment]
closed with #369

**Comment by Jeff-Thompson12** [comment]
Soo...I'm reopening because I noticed that when you click on the button a "shadow" appears and the "shadow" is red.

![image](https://user-images.githubusercontent.com/85879620/216706785-7790d44e-4d33-4897-85a6-fac3e751fede.png)

**Comment by Jeff-Thompson12** [comment]
@Robert-Krajcik I also noticed that even though the delete option is not present for admin users, the `introJS` still has a section for it.

**Comment by Robert-Krajcik** [comment]
Good catch @Jeff-Thompson12 on the `introJS`
I'll make another PR for this and the "button shadow" issue.

**Comment by Robert-Krajcik** [comment]
Finally closed with PR #401 `rk 366 edits_del_option2`
