### ISSUE TITLE
generate_comm_data left_join gives "matches multiple rows" warning

### ISSUE THREAD

**Issue by Robert-Krajcik** [pharmaR/riskassessment#391]
Some packages, like `Tplyr`, sometimes have multiple versions coming out on the same month.
The `versions_with_dates` DF, extracted from callling `get_latest_pkg_info(pkg_name)`, shows that for `Tplyr`:

![image](https://user-images.githubusercontent.com/75215958/216988398-06df28ce-a066-42bb-9a12-79e73d909136.png)

I suggest using a different approach.
Instead of using `'left_join` we slot the version into the `pkgs_cum_metrics` data first 
and then summarize by month and year.

**Comment by AARON-CLARK** [comment]
closed with #392
