### ISSUE TITLE
renv/GHA Cleanup

### ISSUE THREAD

**Issue by borgmaan** [pharmaR/riskassessment#399]
A few items to clean up in the `renv`/GHA realm:

- `fontawesome` should get upgraded to the compatible version (0.3.0) in [`renv.lock`](https://github.com/pharmaR/riskassessment/blob/dev/renv.lock#L752-L762) to avoid needing to re-install it during the execution ([here](https://github.com/pharmaR/riskassessment/blob/fb6b17a1df66ef6976321abe7a0505e2f21f98e4/.github/workflows/R-CMD-check-dev.yaml#L55), [here](https://github.com/pharmaR/riskassessment/blob/fb6b17a1df66ef6976321abe7a0505e2f21f98e4/.github/workflows/R-CMD-check-master.yaml#L54), and [here](https://github.com/pharmaR/riskassessment/blob/fb6b17a1df66ef6976321abe7a0505e2f21f98e4/.github/workflows/test-coverage.yaml#L32))
    - This will allow the app to be run without issue after `renv::restore()` and will save some time on each applicable GHA run 
- There is currently a [warning thrown](https://github.com/pharmaR/riskassessment/actions/runs/4115324874/jobs/7103884662#step:6:1) on all runs of `r-lib/actions/setup-renv`. This should be investigated and remedied if possible.

**Comment by AARON-CLARK** [comment]
> * `fontawesome` should get upgraded to the compatible version (0.3.0) in [`renv.lock`](https://github.com/pharmaR/riskassessment/blob/dev/renv.lock#L752-L762) to avoid needing to re-install it during the execution ([here](https://github.com/pharmaR/riskassessment/blob/fb6b17a1df66ef6976321abe7a0505e2f21f98e4/.github/workflows/R-CMD-check-dev.yaml#L55), [here](https://github.com/pharmaR/riskassessment/blob/fb6b17a1df66ef6976321abe7a0505e2f21f98e4/.github/workflows/R-CMD-check-master.yaml#L54), and [here](https://github.com/pharmaR/riskassessment/blob/fb6b17a1df66ef6976321abe7a0505e2f21f98e4/.github/workflows/test-coverage.yaml#L32))

@borgmaan, I was just thinking we should upgrade to the [v0.5.0 release](https://github.com/rstudio/fontawesome/releases/tag/v0.5.0) which came out two weeks ago so we can put the `v0.4.0` drama in the past. Also, we can edit notes to mimic @Jeff-Thompson12's suggestion [here](https://github.com/pharmaR/riskassessment/issues/275#issuecomment-1412357452).

**Comment by aclark02-arcus** [comment]
closed with #400
