### ISSUE TITLE
Package metrics should match version of package in package table

### ISSUE THREAD

**Issue by borgmaan** [pharmaR/riskassessment#412]
There is currently a bug that allows for metrics to be written to the `package_metrics` table to be derived from a version of the package that does not match the version logged in the `package` table. 

Details can be found in [this comment](https://github.com/pharmaR/riskassessment/issues/385#issuecomment-1428641592) on #385.

**Comment by Robert-Krajcik** [comment]
Hi @borgman
Thanks for looking into this!

**Comment by Borgman** [comment]
> Hi @Borgman Thanks for looking into this!

hey, he is @borgmaan :D I am Borgman

**Comment by Robert-Krajcik** [comment]
Oops! Wrong Borgman.  Apologies @borgmaan

**Comment by aclark02-arcus** [comment]
Closed with #413 and later with #385
