### ISSUE TITLE
Investigate risk scores with new `pkg_ref` source

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#421]
After switching our bare `pkg_ref(<pkg>)` to...

```
pkg_ref(<pkg>, 
    source = "pkg_cran_remote",
    repos = c("https://cran.rstudio.com"))
```

Our pkg scores have gone waaaay up. Specifically, a lot of `tidyverse` packages were somewhere between .1 to .2 -ish. Now they are all around .3 -ish. I know that the context in which these score are evaluated is integral, but that seems like quite a large swing. After this change get's quantified, maybe we should bring this to the `riskmetric` team to consider and edit?

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK I noticed that this is actually dependent on whether we are using the Github version of `riskmetric` compared to the CRAN version and not the changes to the `pkg_ref()` arguments.

**Comment by AARON-CLARK** [comment]
> dependent on whether we are using the Github version of `riskmetric` compared to the CRAN version

Oh really! So it's probably safe to assume these scores are the "new normal"?

**Comment by Jeff-Thompson12** [comment]
Yes, I just verified this to be the case. It may be worth asking the team if they expected those changes in the scores for `tidyverse` packages.

**Comment by AARON-CLARK** [comment]
closing, but I agree. Will start new issue regarding quantifying GitHub vs last CRAN version.
