### ISSUE TITLE
Db Overview: Add button that redirects to pkg metrics

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#426]
It would be convenient to have a button that allows the user to quickly jump to the maintenance metrics for any package in the database overview. So, three actions would take place. First, switch tab back to "Risk Assessment", then select the package from the control panel, then change sub-tab to "Maintenance Metrics".

Maybe label the new button column: "Explore Metrics"

![image](https://user-images.githubusercontent.com/17878953/220139418-cd84f3f2-206f-4909-b85a-47155b91b591.png)

**Comment by Robert-Krajcik** [comment]
Merge of PR #448 addressed this issue.  Closed.
