### ISSUE TITLE
Report Bugs always "No"

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#432]
![image](https://user-images.githubusercontent.com/17878953/220739192-acde88fa-68fb-4285-8a6a-6099f4087387.png)

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK did you reinitialize database.sqlite?

I suppose I should write the code in such a way where that's not necessary. It does show a problem we face when `riskmetric` changes outputs though.

**Comment by Jeff-Thompson12** [comment]
![image](https://user-images.githubusercontent.com/85879620/220740241-04239c6b-a9d6-433d-9dd9-e70307d39df8.png)

**Comment by AARON-CLARK** [comment]
Excellent. Re-initializing worked:

![image](https://user-images.githubusercontent.com/17878953/220740750-399bf126-0cc1-4868-8388-21b61bf89478.png)

However, why is my footer text is different than yours @Jeff-Thompson12 ?

**Comment by Jeff-Thompson12** [comment]
Because I evidently don't follow my own advice.

I temporarily changed the footer while working on the PR but decided to change it back. Then I never reinitialized.

**Comment by AARON-CLARK** [comment]
closing as there is really no issue.
