### ISSUE TITLE
`{riskmetric} v0.2.0` available

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#433]
On GitHub for now. I assume it will be on CRAN soon. Can upgrade using `remotes::install_github("pharmaR/riskmetric")`

Details on the new release:
https://github.com/pharmaR/riskmetric/blob/master/NEWS.md#riskmetric-020

>We now have a Hex Logo! #233.
Number of download assessment can now take a specified number of days. #258. 
A new assessment was added for determining the size of the codebase. #66.
Fixed an issue of some scores returning negative numbers instead of values between [0,1].
A new assessment was added for the presence of a bug report URL for the package.
A new assessment was added to score the dependency footprint of a package.

I think we should open separate issues to make sure we are ingesting all the new assessments appropriately.

**Comment by Robert-Krajcik** [comment]
Closed with Merge of PR #436
