### ISSUE TITLE
DOCX and PDF reports fail on shinyapps.io

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#458]
https://rinpharma.shinyapps.io/riskassessment/

The logs:
![image](https://user-images.githubusercontent.com/17878953/225181423-a6fe8b0e-664d-4caa-ba51-67196cda9b88.png)

Notice they fail on the [v0.1.0 deployment ](https://rinpharma.shinyapps.io/riskassessment_v010) and the recent [v0.1.1 deployment](https://rinpharma.shinyapps.io/riskassessment/) which tells me no recent code changes since last release caused this to fail.

**Comment by aclark02-arcus** [comment]
closed with #734
