### ISSUE TITLE
App Data Storage

### ISSUE THREAD

**Issue by Jeff-Thompson12** [pharmaR/riskassessment#461]
Currently we have all of the application system files in the `inst/app/www` folder. This adds all those files to the folder structure of the application in the browser (e.g. Add `/www/sql_queries/create_comments_table.sql` to the end of the address bar when running the application and you will get a download of that file).
<img width="500" alt="Snag_52f3e2b" src="https://user-images.githubusercontent.com/85879620/225618581-91ba87db-023c-47b6-b65b-2c8b1c0773e5.png">
<img width="300" alt="Snag_52f5184" src="https://user-images.githubusercontent.com/85879620/225618600-98ec1543-1133-4ec9-8262-e5cb2d4d4b14.png">

I imagine that this is unintended/undesired behavior.

**Comment by AARON-CLARK** [comment]
Partially completed with moving report downloads to a new folder in `inst/` (#490)

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK I think this is done unless you know something I don't know. I had already moved the SQL files. The only files left in `app/www/` are the ones we need bundled on deployment.

**Comment by AARON-CLARK** [comment]
Discussed 5/23. Done!
