### ISSUE TITLE
Allow a Single Decision Category

### ISSUE THREAD

**Issue by Jeff-Thompson12** [pharmaR/riskassessment#466]
Allow a user to configure the application to utilize only one decision category.

This would be an enhancement to #459.

**Comment by AARON-CLARK** [comment]
I'm not so sure this is necessary given results from the R Val Hub's [case study research](https://github.com/pharmaR/pharmaR.github.io/pull/88/files#diff-f1de8bb22ea6da38c4b421dd91f02a6693583e08416e5f2bbc4034d00e510d31R13).

> There was a common theme of categorizing package quality into two or three risk categories.

I'm going to close this issue and remove it from our roadmap.
