### ISSUE TITLE
Appsilon Consultation focus

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#479]
As a result of winning 'best app' at shiny conf 2023, we won the opportunity for a 1-hour consultation with Appsilon staff Engineer Pedro Silva. As such, we should try to use his time wisely to help guide our development towards something valuable for the app.

For example, if we wanted to host a public version with persistent, shared annotations as a public demo, perhaps they can suggest architectural decisions that would help guide us? It doesn't need to be exactly that, but that's sort of where my head is at trying to leverage this opportunity.

Here are some ways in which they've helped past clients: [case studies](https://casestudies.appsilon.com/)

**Comment by aclark02-arcus** [comment]
Even though we didn't meetup with Pedro, it's time to close this issue since (1) its over a year old and (2) appsilon contributors have already worked on the project and (3) given us recommendations.
