### ISSUE TITLE
Initialize metric weights from config file

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#482]
Right now, metric weights are initialized from a sql table, but it would make more sense for the sql table to be initialized with metric weights stored in the config file. If metric name not included in the config, it should received default weight of 1. To remove a metric, it should receive weight of 0.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK Currently we are forcing the weight for `covr_coverage` to be 0 in the app. Do we want to change this? Or should this PR force that value to be 0 as well?

**Comment by AARON-CLARK** [comment]
closed with #529
