### ISSUE TITLE
Decision automation based on any individual metric

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#483]
See comment for context: https://github.com/pharmaR/case_studies/issues/3#issuecomment-1118566145

Automatic decisions on pkg risk score make sense, but according to use cases from several pharma companies, often times these have to reject a package based on failure to meet a specific metric threshold. In the example above, Roche had to reject a few CRAN pkgs from their GxP environments because they didn't meet their thresholds for test coverage or even community usage (downloads per year). As such, we the `riskassessment` app should have a way (in the config file and via the decision automation section) to set these pkg exclusion thresholds for any metric.

Some more thoughts:
- Would need new column on pkg upload summary table when an decisions is made automatically, citing the source for the decision - maybe call it "Pkg decision reason". If accepted/ not accepted due to pkg score, the displayed value could be "pkg score with in range" However, if a metric-level exclusion was made, some text could be shown to display how that criteria wasn't met.
- If the metric is `NA`, perhaps the default behavior would be to not exclude right away, but also don't accept (if it meets the pkg risk score threshold).

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK Design question: allowing decision based on individual metrics is basically setting up a process flow. The question to me is should decisions based on the risk score be kept as a unit? Or should we break them out by decision category?

In other words this:

1. metric1 rule
2. risk score rule
3. metric2 rule

compared to this:

1. metric1 rule
2. low risk score rule
3. high risk score rule
4. metric2 rule

If we break them out, those rules can be added anywhere in the process flow.

**Comment by AARON-CLARK** [comment]
> If we break them out, those rules can be added anywhere in the process flow.

Wow, so related to #601. So, I haven't thought about it much! So, just to explore what that process could look like out loud, let's say we have the following rules...

1. code coverage > 50%, then high risk.
2. pkg risk score > .65, then high risk
3. No maintainer, then high risk
4. pkg has over 20 dependencies, then medium risk
5. pkg risk score > .42, then medium risk
6. no place to report bugs > .42, then medium risk

Automated decision for high risk should probably be processed first, right? So processing should occur from "high" to "low" risk? Which assumes there is an order / hierarchy to the decision categories? 

So, let's say fictitious package `{xyz}` passes the first 2 steps, but then "fails" at step 3. There is no maintainer... so the pkg is labeled as "high risk". Honestly, I know I put the 'risk score > .65' rule above the 'no maintainer' rule, but I feel like in general, app deployers / admins would probably want to put individual metrics first, then risk score rules last for each decision category since we are essentially asking users to rank rules from most important to least important, correct? It is possible for multiple rules to be violated, be we want to just know (and report) the first most important rule that gets violated, if any.

As such, if all the "high risk" rules passed, and then # 4 was violated (the pkg had 25 dependencies), I'd want to know that before knowing the pkg score was > .42. So, that was just a really long exercise to say "yes, I think it'd be important to break out each risk score rule".

Just expanding on the example above, it may be nice to have an optional "ELSE" option too. Basically a # 7... for example, if a pkg passes all the checks, maybe it get's automatically categorized as "Low risk".

**Comment by Jeff-Thompson12** [comment]
Yes, the decision process I have set up is a flow and once a decision is made it breaks out of the loop. That is why I had the thought of breaking the risk score up into individual decision categories instead of one block. The rules are sortable so I am not worried about the ordering since the user has complete control over it.

> Just expanding on the example above, it may be nice to have an optional "ELSE" option too. Basically a # 7... for example, if a pkg passes all the checks, maybe it get's automatically categorized as "Low risk".

I hadn't thought of that and I agree that would be a good addition.

**Comment by Robert-Krajcik** [comment]
I am able to use `~is.na(.x)` and that satisfies `rlang::is_formula()`
But it is not clear to me how to specify something like `> 20` or `< 50%` that satisfies
`rlang::is_function()`
Can you elucidate on this?

**Comment by AARON-CLARK** [comment]
closed with #632
