### ISSUE TITLE
Warning on 'loggit_json' database config

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#503]
Sorry @Jeff-Thompson12, I should have re-tested this again before merging into `dev`.

![image](https://user-images.githubusercontent.com/17878953/232783481-c9a1c645-e6a5-421d-b75f-4c9740d35111.png)

**Comment by Jeff-Thompson12** [comment]
Easy fix. I will add it to #501. That PR is being left in draft at the moment because I was anticipating one or two of these to slip through.

**Comment by Jeff-Thompson12** [comment]
Actually resolved with #499.
