### ISSUE TITLE
Confusing messaging on pkg upload progress bar

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#515]
![image](https://user-images.githubusercontent.com/17878953/236542368-484b9bcd-71d5-446b-b485-7372ed446aa7.png)

The messaging above really only made sense when folks were uploading pkgs via a CSV file and the pkg version didn't align with the current version available on CRAN. Now that we can upload pkgs with a `selectizeInput()` or automatically via the new `Dependencies` tab, this lingo doesn't make sense here. Would be great if we only dropped the "...not '0.0.0'" phrase in these cases.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK This will be resolved when #513 is finished, but I can understand doing a small patch PR.

**Comment by imran3004** [comment]
Closing the issue as the PR is merged to `dev` branch.
