### ISSUE TITLE
Next Release of `{riskassessment} v1.0.0`

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#540]
`master` is currently on version `v0.1.1` and we've made [a lot of changes](https://github.com/pharmaR/riskassessment/blob/dev/NEWS.md) since our last release.

Prior to our next presentation obligations June 27th (Rval Hub all-hands) and July 21st (UseR! Basel), we should consider cutting a new release so that our latest code hits `master` a week or two before. As such, we also need to discuss

* Which features we want to get in the door before then?
    * I could wait for #527 to wrap up (its really close) and then cut all other PRs off so that we have something fresh for June 27th. Then that gives us a month to get other PRs through for July 21 talk in Basel. Any objections? Anything you think should be included before the June 27 talk?

* Depending on discussion above, should we increment to a minor (v0.2.0), or major (v1.0.0) release? 

    * I would argue at least a "minor" status given there have been plenty of new features to justify the shift. The new config file with embedded app controls being the primary driver. I would think that adding the "pkg explorer" features may bump us into a major release. Not sure if we can target that in time for the July presentation though given there are a lot of steps to complete before it. I also feel like a major release should have a solution for #504.

Thoughts? Comments? Discussion?
Quick link to [Cutting a new release ](https://github.com/pharmaR/riskassessment/wiki/Cutting-a-new-release) wiki.

**Comment by AARON-CLARK** [comment]
#478 seeks to furnish the "deployments" vignette with more info regarding how to use the config file. This will need to be completed before we can push to `master`

**Comment by Jeff-Thompson12** [comment]
Here's a list of items needing to be addressed (IMO) before the next release. I will be editing this comment as things are added or removed.

- [ ] Either complete #533 or add back checks to ensure code_covr has a weight of 0
- [ ] Remove ability to assign roles when multiple users are selected
- [ ] Update vignettes and site

**Comment by AARON-CLARK** [comment]
All systems go. Commence with next release!

> * [x]  Either complete [Create card for `covr_coverage` #533](https://github.com/pharmaR/riskassessment/issues/533) or add back checks to ensure code_covr has a weight of 0
> * [x]  Remove ability to assign roles when multiple users are selected [Disable roles when editing multiple users #543](https://github.com/pharmaR/riskassessment/issues/543)
> * [x]  Update vignettes and site [Update User Guides #542](https://github.com/pharmaR/riskassessment/pull/542)
