### ISSUE TITLE
Disable roles when editing multiple users

### ISSUE THREAD

**Issue by Jeff-Thompson12** [pharmaR/riskassessment#543]
An admin should not be able to assign roles to multiple users at once since roles are tied to the administrative privilege.

**Comment by AARON-CLARK** [comment]
For context:
![image](https://github.com/pharmaR/riskassessment/assets/17878953/15a57e9f-f711-4179-9307-25be4640fd46)

**Comment by Jeff-Thompson12** [comment]
Closed with #544
