### ISSUE TITLE
Deleting Packages

### ISSUE THREAD

**Issue by Jeff-Thompson12** [pharmaR/riskassessment#546]
A user with the `delete_package` privilege can remove packages from consideration. However, the list of packages will include some where final decisions have been made. Should we only be completely populating this list if the user also has the `revert_decision` privilege?

**Comment by AARON-CLARK** [comment]
hmmmm, Good question. I see what you're saying: technically if a `delete_package` user wanted to revert a decision, but didn't have that permission, they could just delete the package, and then re-upload the package (assuming they also have the `add_package` privilege.

I think if you are an `admin`, you'd just have to acknowledge that that is a possibility, right? If you allow someone to delete packages, they can delete packages, whether it has a decision made or not.

We can keep thinking about it, but that's the way I'm leaning right now.

**Comment by Jeff-Thompson12** [comment]
I guess I was also thinking that we should provide some warning if a user was trying to delete a package where a decision has already been made.

Another possibility is that only packages currently "under consideration" can be deleted, requiring a decision to be reverted to delete a package where a final decision has already been made.

**Comment by AARON-CLARK** [comment]
Warning is a good idea 👍🏼 

I think marking packages with labels like "under consideration" is a good idea (hence #495), but I think we can pursue that later.

**Comment by AARON-CLARK** [comment]
old / stale
