### ISSUE TITLE
Tarball storage

### ISSUE THREAD

**Issue by Jeff-Thompson12** [pharmaR/riskassessment#571]
Currently in the developmental branch we are downloading tarballs when a package is uploaded to the database. We are doing this using the tarball URL provided by the package reference object produced by `riskmetric::pkg_ref()`.

Should we consider only storing tarballs and source documents per session? Since we are collecting package name and version, we should be able to download past versions from the CRAN Archive. This could complicate things when we expand usage of the application to include Bioconductor packages (and maybe even Github), but may be a necessary complication.

Does this pose any incongruities with the `riskmetric` assessments being calculated? Is there any reason to think that a tarball downloaded using the CRAN Archive would differ from the originally assessed version (i.e. do we actually need to store the tarball at time of assessment)?

**Comment by AARON-CLARK** [comment]
We should confirm that any new pushes/changes to a package on CRAN or Bioconductor equates to a pkg version change.

**Comment by jthompson-arcus** [comment]
Closing this issue. Storing tarballs at time of assessment seems to be the best solution (Also noting that when a package is archived on CRAN, the URL would change anyways).
