### ISSUE TITLE
Clearly identify which cards are `riskmetric` derived

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#573]
So, very very soon, we plan to combine the Maint metric and Comm Usage tabs into one (as mentioned [here](https://github.com/pharmaR/riskassessment/pull/539#pullrequestreview-1526397389) & related to #498). However, there are a few cards on the Comm Usage tab that technically aren't `riskmetric` assessments YET they add a lot of value/context when interpreting the plot. Yet another non-`riskmetric` card is being added with #572. With that said, I don't see them going away. As such, we don't want to confuse our audience into thinking that these cards are all `riskmetric` derived, so we should delineate between the two somehow. Maybe we add an asterisk on those cards with a footnote somewhere that explains that these cards are "*Provided for additional context. Not an `{riskmetric}` assessment, so they will not impact risk score". Alternatively, we could change the border color or something.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/e5fd702a-e9ae-4c7f-9c1b-c960f009002b)

**Comment by Robert-Krajcik** [comment]
Resolved with merge of PR #590
