### ISSUE TITLE
File Browser crashes when switching pkgs and previewing certain files

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#579]
The app crashes on `dev` with the following error when you try to open these files while browsing source data from the `{xts}` pkg:

```
Warning in file(con, "r") :
  cannot open file 'source/xts/R/ggplot2.zoo.R': No such file or directory
Warning: Error in file: cannot open the connection
```

![image](https://github.com/pharmaR/riskassessment/assets/17878953/9b18b839-5771-40a3-a6ef-aedd9830a35f)

**Comment by AARON-CLARK** [comment]
Looks like it may be an issue with how the tree updates when switching from package-to-package. I just switched from `zoo` to `tidyCDISC` and some files update, like the `description` file seen here, but not the R/folder. Same is true for vignettes - they are all `zoo` vignettes. So when the app is told to go preview these files, it couldn't look them up because those files don't exist for `tidyCDISC`.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/bc2a6280-68e6-4db3-a8d5-58abbbaf4324)

**Comment by Jeff-Thompson12** [comment]
So I found this quite puzzling because I had checked this specific issue while integrating the code, but it appears that I introduced breaking changes in later commits. It appears that rendering the UI in the server is causing the tree to break.
