### ISSUE TITLE
Migrate from `{jsTreeR}` to `{shinyTree}`

### ISSUE THREAD

**Issue by Jeff-Thompson12** [pharmaR/riskassessment#585]
Related to #579, there is idiosyncratic handling of HTML outputs in the `{jsTreeR}` package. I have worked with the package creator to satisfactorily fix some of them but not others, particularly the one causing the issue in #579. These non-standard behaviors will make the code containing `{jsTreeR}` functions hard to maintain going forward.

While it is remarked that `{shinyTree}` does not have as many features, I believe the benefits outweigh the cost to migrate to that package instead.

**Comment by AARON-CLARK** [comment]
closed with #635
