### ISSUE TITLE
Add border to "Package Metrics" header/ selectInput()

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#595]
I wish the down-arrow was enough, but it's too hard to tell that this header is also a `selectInput()` used to toggle through each page. I just adding a border around it will help users realize it's something they can toggle.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/b115d0a0-99bf-4e28-9fe5-c7fa6aa96d23)

**Comment by Robert-Krajcik** [comment]
Thanks @AARON-CLARK and @Jeff-Thompson12 for fixing this Norman Door.

**Comment by AARON-CLARK** [comment]
closed with #599
