### ISSUE TITLE
Add UI feedback on the "Source Explorer" tab

### ISSUE THREAD

**Issue by nicolekjones** [pharmaR/riskassessment#625]
For larger packages that take a bit of time to unpack it might be nice to see some sort of indicator that the app is working on the backend. Possibly with shinycssloaders ?

**Comment by AARON-CLARK** [comment]
Thanks for your feedback @nicolekjones. This issue is closed on the `dev` branch with #637. I'll close this issue once it get's to `master`.

**Comment by AARON-CLARK** [comment]
Apologies @nicolekjones, I forgot to show you the solution! Now there is an animated progress bar with messages sharing what the app is doing in the background, informing the user.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/c7c6ebf4-70c6-4e72-9d64-30b2f5a86e12)

**Comment by AARON-CLARK** [comment]
Not available on `master` with v3.0.0! 
https://github.com/pharmaR/riskassessment/releases/tag/v3.0.0
