### ISSUE TITLE
Reactivity in package control panel lost, sometimes

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#627]
This isn't the first time this has happened to me, but I was on `dev` this morning and found that packages that I just uploaded were not added to the package control panel right away.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/93284273-26f7-4d62-a6ac-78b8610dbd5f)

After I re-loaded the app however, they were there. So they definitely made it into the database.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/66fb206e-7769-491f-b657-ec60d7c0352f)

I tried it again, and the issue seemed to go away.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/24dffc42-8b87-4a2b-8cf7-90dea3f8d531)

Ideally, it would be nice to try and figure this one out, but if we can't, I think a great way to cover our tracks would be to add an "Explore Metrics" button in the "Summary of Uploaded Pkgs" after upload, similar to the buttons seen on the database view tab:

![image](https://github.com/pharmaR/riskassessment/assets/17878953/294f172e-2041-41ca-8434-3297d9fd08c1)

**Comment by Jeff-Thompson12** [comment]
Do you have any idea how one might replicate this issue?

**Comment by Jeff-Thompson12** [comment]
We could also do something akin to what is going on with the upload package selectize. We could have a reactive value that gets recalculated whenever someone opens that dropdown. If we use `reactiveVal()` we can set the choice update to only trigger if there is a change.

**Comment by AARON-CLARK** [comment]
> Do you have any idea how one might replicate this issue?

Not sure what I was doing before this happened. I think I had started with a fresh session.

**Comment by AARON-CLARK** [comment]
> We could also do something akin to what is going on with the upload package selectize. We could have a reactive value that gets recalculated whenever someone opens that dropdown. If we use `reactiveVal()` we can set the choice update to only trigger if there is a change.

That's not a bad idea. If we want to wait till we find the driver behind the bug, we could, but implementing a solution like this seems like it would work.

**Comment by Robert-Krajcik** [comment]
Hi @AARON-CLARK 
I am unable to reproduce this issue.  Seems to be running fine for me.
I am thinking we should just close this issue.  What are your thoughts?

**Comment by AARON-CLARK** [comment]
yep, let's close it. I think it's especially helpful now that we have the "explore metrics" button in the upload summary table.
