### ISSUE TITLE
Function Explorer: Auto navigation to highlighted rows

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#644]
After merge of #637:

For both 'R Source Code' and 'Testing Files', add `[Prev]` & `[Next]` buttons that would allow users to jump to the previous or next highlighted row displayed. Optimally, when these files are even "opened" or "clicked", the page should automatically scroll down to the first use of the function call. In some cases, these function will be used in a `utils.R` file which could have hundreds of lines of code. It pretty tedious to scroll down to find them... although it appears the chrome `[Ctrl+F]` also works to find those highlighted rows more quickly. In the example below (for `tidyCDISC`), I had to scroll about 1/2 way down a utils file before I found it.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/0477415d-cb7a-4727-a752-53994f4b4609)

**Comment by narayanan-iyer-pfizer** [comment]
closed
