### ISSUE TITLE
remove suggests from riskcalc weights table

### ISSUE THREAD

**Issue by Robert-Krajcik** [pharmaR/riskassessment#646]
Suggests is not used as a `riskmetric` weight and needs to be removed from the table below
id="assessmentInfo-riskcalc_weights_table"
![image](https://github.com/pharmaR/riskassessment/assets/75215958/790a3543-75fc-4f0a-8ceb-3497293507ae)

**Comment by AARON-CLARK** [comment]
closed with #648
