### ISSUE TITLE
Database View: select "all" pkgs for report downloader

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#649]
We already have the functionality to download multiple reports, but our pkg selection is restricted by `DT` & pagination. Ideally, we should allow users to download mass quantities of reports... maybe hundreds at a time. So, once #619 is completed, I'm thinking a good use case would be a user looking to filter the list down to pkgs that were uploaded on (or after) a certain date and that were considered "low" risk, for example. Those are the reports that the org may need to submit to their "pkg inclusion" governing body.

To start, we need two things:

1. a prominent checkbox (probably below the table, nearly all the report configs) that allow users to select all pkgs, subject to any filters introduced by #619 
2. I think we need the ability to view more than 15 reports on the page so . Do we create a dropdown with 15, 50, and 100 selections? Showing "All" does make me a little nervous. I do think the checkbox above should grab all the packages defined in # 1, despite what is shown.
3. If more pkgs are shown on the page from # 2, it doesn't make sense to have the report configs below the table, so that would actually make more sense as a (collapsable?) side panel on the left-hand side.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/9ac2b482-7142-4891-9dd6-034762d05075)

**Comment by Jeff-Thompson12** [comment]
An alternative to creating a side panel could be to restrict the max size of the data table window and make it scrollable.

**Comment by AARON-CLARK** [comment]
closed via #655
