### ISSUE TITLE
Get metric value column to wrap for Maint Metric table in PDF output

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#651]
> I know this issue with the PDF reports predates your PR, but if you know of a way to fix this that would be great. Otherwise we need to open another PR.
> ![image](https://user-images.githubusercontent.com/85879620/269396666-7e7ceeeb-3f80-478e-bd49-171405105126.png)

I did try some other things; namely, `knitr::kable(format = 'latex', booktabs = TRUE, escape = FALSE)` paired with `kableExtra::column_spec(3, width = "3cm")` which works as expected for the comm table. However, I couldn't get it to work for the Maint table... frustrating 😵‍💫. I found that anytime I changed the format away from `knitr::kable(format = 'pandoc')`, the PDF render just spin for mins and mins, never finishing. So, I left some of that code in the .Rmd file, but just commented out. I'll initiate a new issue.

_Originally posted by @AARON-CLARK in https://github.com/pharmaR/riskassessment/issues/634#issuecomment-1729488758_

**Comment by aclark02-arcus** [comment]
closed with #734
