### ISSUE TITLE
Describe the card's possible meter visuals

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#652]
For those unfamiliar with `{riskmetric}` or metric scores, and given the recent merge of #634, it seems we may need some sort of legend that could help explain these graphics. Per discussion at today's dev meetup, it would seem that perhaps this would be best suited in both the `introjs` steps and also the `Assessment Criteria` tab. There is a lot of explain:

- [ ] No meter, assessment not found warning sign
- [ ] Meter displaying 0
- [ ] Meter displaying 1
- [ ] Meter between 0 and 1
- [ ] Meter displaying NA (assessment value exists, but no score)

Also, perhaps we should mention how the scores work (i.e. that 1 is bad and indicates high risk while 0 is good and indicates low risk).

**Comment by aclark02-arcus** [comment]
closed with #760
