### ISSUE TITLE
Switch Report Configs storage to DB

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#661]
#### Why use txt files?
I don't think the app deployer should have to learn about & specify yet another folder/file system in `inst/db_config.yml` for storing these preferences. It would seem prudent to leverage our user-based credentials db to store this information, no? There could be a table to store org-level and a table for user-level preferences. Thoughts?

_Originally posted by @AARON-CLARK in https://github.com/pharmaR/riskassessment/pull/645#pullrequestreview-1680112464_

**Comment by aclark02-arcus** [comment]
this issue is stale and this feature never really hit `master`, at least from the perspective of using txt files to execute the proposed functionality in #645.
