### ISSUE TITLE
Allow users to "vote" on a risk decision

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#662]
As we near a more collaborative state of a demo app hosted on a platform that maintains persistent storage, it would be prudent to offer up some more features the explicitly records the opinions of a `reviewer`, since that will be the primary role leveraged. My thought is that `reviewer`s would be able to actually submit a "user decision" for any package, but then `lead`s and `admin`s would be able to submit both a "user decision" and a "final decision". Or maybe call it "Org decision"? Either way, the purpose of the 

* user decision is purely for context, to be displayed and/or summarized on the build report tab and possibly the db overview tab. There could be several user decisions on a package since anyone in the `reviewer` role can submit one.
* final decision would mimic the current "overall decision" features and logic we have today. That is, only 1 can be specified at a time and once made, it would "lock down" that package (for that review timepoint / upload date at least). Only an `admin` or `lead` may submit.

Shifting in this direction will make the it extremely clear which way a reviewer is leaning for any given package. And since these reports are intended to be handed off to the GXP inclusion gatekeepers, it makes sense that the reviewers evaluation / impressions be made clear.

**Comment by aclark02-arcus** [comment]
I'm unsure whether this is a good idea or not. I'm not sure how practical it is for the everyday org. If anything, I think that #487 is more important / relevant. As a result, I'm going to close this one.
