### ISSUE TITLE
Non-credentialed deployment

### ISSUE THREAD

**Issue by Jeff-Thompson12** [pharmaR/riskassessment#700]
We need to be able to specify a deployment (probably in the configuration file) that does not use `{shinymanager}`. This is to accommodate organizations that want to use `{riskassessment}` as a means to build reports and are not concerned with the decision making and other such features.

**Comment by Jeff-Thompson12** [comment]
It appears that we can achieve usage of roles when deployed on Shiny Server or Connect by making use of the objects `session$user` and `session$groups` in a non-credentialed deployment. This would require usage of a default privilege and not requiring an admin role.

**Comment by aclark02-arcus** [comment]
closed with #703
