### ISSUE TITLE
Meter color off in HTML reports

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#727]
I just realized the meter's color hasn't been changed in the downloadable HTML report yet (see below). 

![image](https://github.com/pharmaR/riskassessment/assets/17878953/25aaa956-5466-42e4-a0c7-e7ef5ed006d0)

_Originally posted by @AARON-CLARK in https://github.com/pharmaR/riskassessment/pull/723#pullrequestreview-1780479716_

**Comment by aclark02-arcus** [comment]
closed with #728
