### ISSUE TITLE
Shiny Notification Displays

### ISSUE THREAD

**Issue by Jeff-Thompson12** [pharmaR/riskassessment#732]
`{shinymanager}` imports some custom CSS for the shiny notification elements. This is attached to the webpage via singletons and gets pulled in with the `shinymanager:::admin_ui()` function. This results in notifications displaying differently in the riskassessment app for non-admin users compared to admin.

Solution is to incorporate the entire CSS from shinymanager and apply it to the whole application.

**Comment by Jeff-Thompson12** [comment]
It should also be noted that because of how the CSS elements are incorporated, we cannot overwrite them our own styling in app/www/css. The styling from shinymanager will take priority. Most simplistic solution is to incorporate their styles for the whole application.

**Comment by AARON-CLARK** [comment]
closed with #733
