### ISSUE TITLE
App logo outdated in reports

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#737]
For HTML / DOCX / PDF

![image](https://github.com/pharmaR/riskassessment/assets/17878953/21b68cfc-9688-4c83-9873-1eb0131c99f7)

We should seek to mimic the shiny app's logo, which has been a lighter rendition for a few months now:

![image](https://github.com/pharmaR/riskassessment/assets/17878953/c7ac5331-42a6-43ae-b44e-47e9bcae30af)

**Comment by aclark02-arcus** [comment]
closed with #759
