### ISSUE TITLE
Package Dependencies Issues, Part II

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#738]
As a follow up to #734, we discussed adding the following: 

### 1. Suggests

Also, there is no option to include or exclude "Suggests" in this table. Honestly, this is something that I would love to be controlled from the config file (related to #720), but in the app, we can give users the option to choose "with" or "without Suggests"? How about if the "Package Dependencies" report config is selected, another material switch appears (similar to the one below) that asks users to include suggests. Perhaps it maintains state from the Package Dependencies tab.... or not if that's too tricky.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/1b9c1cbf-a138-47db-b5f9-dbcc14860ee2)

### 2. Score

I also feel like the score column can be a little confusing, but only because it's not well defined. Do users know: if there is no score present in the DB, there is no score? A potential solution would be to fill these cells with "Not Assessed" or "Not uploaded". I'm open to suggestions!

### 3. PDF margins

Do the margins on PDF still have to be reduced now that we are getting columns to wrap? I think it can look a little funny when everything is so far to the left. Also, I noticed, things are centered vertically in the page too. Not sure if that's necessary, so if that's an easy option to toggle off, I think I'd prefer if content showed up at the top of the page, where appropriate.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/0cb92ffd-67cd-4dff-9684-06af8df8624f)

### 4. PDF headers should be title case

posted by @Jeff-Thompson12 on #734: 

>The HTML report hides issues with the dependency table headers that show up on the PDF DOCX outputs.

![image](https://github.com/pharmaR/riskassessment/assets/85879620/3743a92d-ccbc-401f-b63b-6d5f185bb9d5)

_Some content originally posted by @AARON-CLARK in https://github.com/pharmaR/riskassessment/pull/723#pullrequestreview-1780479716_

**Comment by aclark02-arcus** [comment]
closed with #750
