### ISSUE TITLE
Introduce "About" Tab

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#752]
This will be a new tab at the very top, I think can do a few things:

1) absorb the existing "assessment criteria" tab, making this the default sub-tab.

2) have a "Contact" tab, where we can list how folks can get in touch with the R Validation Hub, and especially the development team. There will certainly be links to open a new GitHub issue.

2) introduce a "Contributors" tab, containing the following (with pictures and / or logos)
o	Deployment hosted by ProCogia
o	Current Developers & Companies
o	Past Developers & Companies
o	link to Contact page

**Comment by AARON-CLARK** [comment]
@BarbMik, this might be a good first one to explore working on!

**Comment by aclark02-arcus** [comment]
closed with #761
