### ISSUE TITLE
`MASS` not available in repo

### ISSUE THREAD

**Issue by aclark02-arcus** [pharmaR/riskassessment#776]
![image](https://github.com/pharmaR/riskassessment/assets/162465159/265f0728-0509-4d5f-a634-20f2226ba745)

For `MASS`, per @Robert-Krajcik:
![image](https://github.com/pharmaR/riskassessment/assets/162465159/5663ea44-b71d-47af-8f4c-0013cfeb977a)

**Comment by jthompson-arcus** [comment]
So further investigation shows that `MASS` is not an available package from the repository which is why the version comes in as `character(0)`, not because it uses the old style of versioning.

**Comment by emilliman5** [comment]
FYI, The newest version of MASS requires R v4.4.0. I ran into this same problem when installing tidyverse in a new renv env and had to install from an earlier snapshot. I don' think RA installs the package to run assessment but I wonder if you are doing a dependency search when doing assessment the version of R might matter.

**Comment by jthompson-arcus** [comment]
Hmm, this appears to be precisely what is going on. We are using `available.package()` and it has a built in filter based on R version.

**Comment by aclark02-arcus** [comment]
closed with #808
