### ISSUE TITLE
Add "decision" argument to `upload_pkg_list()`

### ISSUE THREAD

**Issue by aclark02-arcus** [pharmaR/riskassessment#793]
Adding a new arg, called decision to that function. So it could be used like:

    `upload_pkg_list(c("Tplyr","dplyr","dbplyr"), decision = c("Medium Risk", "Low Risk", ""))`

Just a suggestion... maybe we'd want to use a named list instead?

*Originally discussed in #792.*

**Comment by jthompson-arcus** [comment]
The function already accepts a data frame for the package argument. In fact, this is how the function currently works. A user can pass that information in there once we get the point where this function is being exported.
