### ISSUE TITLE
App is failing with error "there is no package called jsonlite" while publishing on shiny server

### ISSUE THREAD

**Issue by MominUmair** [pharmaR/riskassessment#804]
when we are trying to publish the app, it is failing with jsonlite package not found error. And the package is available with 1.8.8 version.
I am using R 4.3.3 with [this branch (demo-procogia-v310)]
I also installed the other dependencies as mentioned.
Please see screen shots.
<img width="539" alt="error" src="https://github.com/pharmaR/riskassessment/assets/121301162/f2437303-6be9-437a-b717-af990d48aa7d">
<img width="498" alt="renvss" src="https://github.com/pharmaR/riskassessment/assets/121301162/8f9f19be-0cf1-4be4-9ee2-e9e50da138db">

**Comment by jthompson-arcus** [comment]
Just to clarify, you are saying that jsonlite v1.8.8 is installed, but when publishing the app, you are getting the not found error?

**Comment by MominUmair** [comment]
@jthompson-arcus yes, the jsonlite v1.8.8 is installed and available for the project, but when I am publishing the app, it is failing with "there is no project called jsonlite".

**Comment by aclark02-arcus** [comment]
Hi @MominUmair, let's put this issue on hold to see how things go once this branch has been deployed on Posit Connect.

**Comment by aclark02-arcus** [comment]
Taking this issue off hold since deployment using a public Posit Connect is no longer an option!

**Comment by jthompson-arcus** [comment]
@MominUmair can you provide more details on why you think this is an issue with the application instead of the deployment environment?

**Comment by MominUmair** [comment]
Hi @jthompson-arcus ,we have 3 R versions available on the server and all have jsonlite installed , but the app is not taking it, however I am checking on the environment side , is it possible for you share any other branch , just to confirm it is not on the infra side.

**Comment by aclark02-arcus** [comment]
Hi @MominUmair, why don't you give `demo-shinyapps.io-v310` a try?

https://github.com/pharmaR/riskassessment/tree/demo-shinyapps.io-v310

**Comment by MominUmair** [comment]
Hi @aclark02-arcus , the issue got resolved, it was failing due to mismatch in the lib path of the renv. the renv installed the packages under the home dir of the user and shiny servers using default system library path. after adding below parameter in the settings.dcf file of the renv folder and reconfiguring the renv resolved the issue. RENV_PATHS_LIBRARY=/opt/R/4.3.3/lib/R/library
the app is up now, you can close this ticket
