### ISSUE TITLE
Package data stored in database is stale/ out of date

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#81]
So, I haven't uploaded a csv of packages to the app in quite some time. So, when working on the CommunityUsageMetrics Tab (specifically, the `Number of Downloads per Month` plot) I noticed that when I selected the `dplyr` package, I was only getting results from as recent as July 2020. I confirmed this by just running the SQL query below, which produces the resulting data frame:

`dplyr_cu <- db_fun("SELECT * FROM CommunityUsageMetrics WHERE cum_id ='dplyr'")`

![image](https://user-images.githubusercontent.com/17878953/100776176-39c08880-33d2-11eb-8399-bc5030a3f49c.png)

I had a hunch that the db only seeks "fresh data" once I upload `dplyr` in a CSV on the `Upload Package` tab. I tested re-uploading and nothing changed (probably because `dplyr` already exists in my db). However, I tried uploading a new package that doesn't yet exist in my db: `stringr` and then re-ran the sql query and found more recent data populated the table, up to Nov 2020:

`stringr_cu <- db_fun("SELECT * FROM CommunityUsageMetrics WHERE cum_id ='stringr'")`

![image](https://user-images.githubusercontent.com/17878953/100777122-6628d480-33d3-11eb-8c59-08755a241426.png)

The fact that the package data used by the app doesn't update may pose a problem for when app users return to packages uploaded a long time ago to re-assess their risk. All of their metrics could have changed after a few months - not just community usage metrics.

So the question becomes, when do update this information? We could determine if the package data stored in the db is old, and if so, render a button that says "Update Metrics" on the side panel & the db dashboard. I don't think we'd want to update metrics automatically since it would (1) waste resources and (2) completely erase the context in which the package was originally reviewed, if applicable.

Thoughts?

**Comment by marlycormar** [comment]
This is a very good observation @AARON-CLARK. The risk of a package is associated with the value of its metrics AND the date the risk is assessed.

I agree with you that it is not a good idea to automatically update packages in the db.

We can also associate a date with a package/version. We can have a new dropdown where you can choose the date the report was ran. This poses a new question: should we create a new entry on the db every time the user uploads `dplyr` for instance? or just one daily? If we decide to go with something along these lines, then the db dashboard should allow users to delete entries in the db.

**Comment by marlycormar** [comment]
Let us discuss in our next meeting. Also, think about adding an 'Update'/'Add' button that will update or add a new entry on the database for the package.

**Comment by aclark02-arcus** [comment]
closing since #493 exists which would better solve the problem.
